import { useState } from "react";

function InputField({type = 'default', currency = 'RON'}){
    const [currencyValue, setCurrencyValue] = useState('RON');

    const currencyCodes = [
    "AFN",
    "ALL",
    "DZD",
    "AOA",
    "ARS",
    "AMD",
    "AWG",
    "AUD",
    "AZN",
    "BSD",
    "BHD",
    "BDT",
    "BBD",
    "BYN",
    "BZD",
    "BMD",
    "BTN",
    "BTC",
    "BOB",
    "BAM",
    "BWP",
    "BRL",
    "GBP",
    "BND",
    "BGN",
    "BIF",
    "KHR",
    "CAD",
    "CVE",
    "KYD",
    "XOF",
    "XAF",
    "XPF",
    "CLP",
    "CNY",
    "COP",
    "KMF",
    "CDF",
    "CRC",
    "HRK",
    "CUC",
    "CZK",
    "DKK",
    "DJF",
    "DOP",
    "XCD",
    "EGP",
    "ERN",
    "ETB",
    "EUR",
    "FKP",
    "FJD",
    "GMD",
    "GEL",
    "GHS",
    "GIP",
    "GTQ",
    "GNF",
    "GYD",
    "HTG",
    "HNL",
    "HKD",
    "HUF",
    "ISK",
    "INR",
    "IDR",
    "IRR",
    "IQD",
    "ILS",
    "JMD",
    "JPY",
    "JOD",
    "KZT",
    "KES",
    "KWD",
    "KGS",
    "LAK",
    "LBP",
    "LSL",
    "LRD",
    "LYD",
    "MOP",
    "MKD",
    "MGA",
    "MWK",
    "MYR",
    "MVR",
    "MRU",
    "MUR",
    "MXN",
    "MDL",
    "MNT",
    "MAD",
    "MZN",
    "MMK",
    "NAD",
    "NPR",
    "ANG",
    "TWD",
    "NZD",
    "NIO",
    "NGN",
    "KPW",
    "NOK",
    "OMR",
    "PKR",
    "PAB",
    "PGK",
    "PYG",
    "PEN",
    "PHP",
    "PLN",
    "QAR",
    "RON",
    "RUB",
    "RWF",
    "SAR",
    "SDG",
    "SRD",
    "SZL",
    "SEK",
    "CHF",
    "STN",
    "VES",
    "ZMW",
  ];

    return <>
    <input type="text" className={type + ' Name'} placeholder={type + ' name'} value={type + ' name'}/>
    <input type="number" inputmode="decimal" placeholder="0,00" />
    <select class="currencySelector" id="currency" name="currency" value={currencyValue} onChange={(e) => setCurrencyValue(e.target.value)}>
    {currencyCodes.map((currency) => {
        return <option value={currency}>{currency}</option>
    })}
    </select>
    <button class="selfDestroyBTN">X</button>
    </>
}

export default InputField;